[project]
name = "recipe-kitchen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JaredAung", email = "133064427+JaredAung@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
]

[project.scripts]
recipe-kitchen = "recipe_kitchen:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
